import {ReactNode} from "react";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function DashboardLayout({ children }: { children: ReactNode }) {
    return (
        <main>
            {children}
        </main>
    )
}