import { ReactNode } from 'react';
import {Container, Header} from '@/shared/components/shared';

export const metadata = {
	title: 'Next Pizza | Корзина',
	description: 'Generated by Next.js',
};

export default function CheckoutLayout({ children }: { children: ReactNode }) {
	return (
		<main className="min-h-screen bg-[#F4F1EE]">
			<Container>
				<Header hasSearch={false} hasCartButton={false} className="border-b-gray-200" />
				{children}
			</Container>
		</main>
	);
}
